name:  Release to PyPI

on:
  push:
    tags:
       - '*'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies for testing
        run: |
          pip install setuptools wheel twine
          pip install .[test]
      - name: Test core with pytest
        run: |
          pytest -v
      - name: Publish on PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.AIND_PYPI_TOKEN }}
        run: |
          python setup.py sdist
          twine upload dist/*
