name: Cython - Python Package using Conda

on:
  pull_request:
    branches: [main]
    types: [synchronize, opened, reopened, ready_for_review]


jobs:
  build-and-test:
    name: Test on (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1
        with:
          python-version: 3.9
      - name: Install WavPack (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install wget
          sudo apt install -y gettext

          wget https://www.wavpack.com/wavpack-5.5.0.tar.bz2
          tar -xf wavpack-5.5.0.tar.bz2
          cd wavpack-5.5.0
          ./configure
          sudo make install
          cd ..

          # check libraries
          ls /usr/local/lib/ | grep wavpack
      - name: Install WavPack (macos)
        if: matrix.os == 'macos-latest'
        run: |
          conda install wget

          wget https://www.wavpack.com/wavpack-5.5.0.tar.bz2
          tar -xf wavpack-5.5.0.tar.bz2
          cd wavpack-5.5.0
          ./configure
          sudo make install
          cd ..
      - name: Install dependencies
        run: |
          pip install Cython
          pip install -e wavpack_cython
          pip install zarr
          pip install pytest
      - name: Test with pytest 
        run: |
          pytest -v wavpack_cython
