name: Python Package using pre-built Linux binaries

on:
  pull_request:
    branches: [main]
    types: [synchronize, opened, reopened, ready_for_review]


jobs:
  build-and-test:
    name: Test on (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v2
      - uses: s-weigand/setup-conda@v1
        with:
          python-version: "3.9"
      - name: Python version
        run: |
          which python
      - name: Install dependencies
        run: |
          pip install Cython
          pip install .
          pip install zarr
          pip install pytest
      - name: Test imports and version
        run: |
          pytest -s tests/test_imports.py
      - name: Test with pytest 
        run: |
          pytest -v 
