name: Python Package using Cython

on:
  pull_request:
    branches: [main]
    types: [synchronize, opened, reopened, ready_for_review]


jobs:
  build-and-test:
    name: Test on ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install WavPack (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt update
          sudo apt install wget
          sudo apt install -y gettext

          wget https://www.wavpack.com/wavpack-5.7.0.tar.bz2
          tar -xf wavpack-5.7.0.tar.bz2
          cd wavpack-5.7.0
          ./configure
          sudo make install
          cd ..

          # check libraries
          ls /usr/local/lib/ | grep wavpack
      - name: Set up Homebrew (macos)
        if: matrix.os == 'macos-latest'
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install WavPack (macos)
        if: matrix.os == 'macos-latest'
        run: |
          brew install wget

          wget https://www.wavpack.com/wavpack-5.7.0.tar.bz2
          tar -xf wavpack-5.7.0.tar.bz2
          cd wavpack-5.7.0
          ./configure
          sudo make install
          cd ..
      - name: Python version
        run: |
          which python
      - name: Install dependencies
        run: |
          pip install Cython
          pip install .
          pip install zarr
          pip install pytest
      - name: Test imports and version
        run: |
          pytest -s tests/test_imports.py
      - name: Test with pytest 
        run: |
          pytest -v
