name: Python Package with multi-threading

on:
  pull_request:
    branches: [main]
    types: [synchronize, opened, reopened, ready_for_review]


jobs:
  build-and-test:
    name: Test on ${{ matrix.os }} - Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install WavPack (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          chmod +x ./.github/scripts/install-wavpack-linux.sh
          ./.github/scripts/install-wavpack-linux.sh

          # check libraries
          ls /usr/local/lib/ | grep wavpack
      - name: Install WavPack (macos)
        if: matrix.os == 'macos-latest'
        run: |
          chmod +x ./.github/scripts/install-wavpack-macos.sh
          ./.github/scripts/install-wavpack-macos.sh
      - name: Python version
        run: |
          which python
      - name: Install dependencies
        run: |
          pip install Cython
          pip install .
          pip install zarr
          pip install pytest
      - name: Test imports and version
        run: |
          pytest -s tests/test_imports.py
      - name: Test with pytest 
        run: |
          pytest -v
